In [1]:
import googlemaps
import pandas as pd
import numpy as np
import time
import requests
import ortools
import json
import urllib
import urllib.request
import itertools
from pprint import pprint
from math import comb
from itertools import combinations, permutations


In [2]:
API_key =  "AIzaSyAEKN-xcnWtB3c65ErptbVLrZYlpRhST9o"
tourist_list = pd.read_csv("Vancouver.csv")

In [3]:
#print all column names in tourist_list
# for col in tourist_list:
#     print(col)

In [4]:
print(tourist_list["city"].unique())

['North Vancouver' 'Vancouver' 'Burnaby' 'West Vancouver' nan
 'New Westminster' 'Surrey' 'Coquitlam' 'Port Moody' 'Maple Ridge'
 'Sechelt' 'Richmond' 'Comox' 'Saanich' 'Comox-Strathcona J' 'Sooke'
 'Quathiaski Cove' 'Revelstoke' 'Brentwood Bay' 'Nanaimo' 'Abbotsford'
 'Port Hardy' 'Port Edward' 'Jasper' 'Improvement District No. 9'
 'Edmonton' 'Gibsons' 'Langley Twp' 'Delta' 'Port Coquitlam' 'Langley'
 'Belcarra' 'Anmore' 'Campbell River' 'Victoria' 'Toronto' 'Malahat'
 'Bowen Island' 'Killarney' 'Cobble Hill' 'West End' 'Greater Vancouver A'
 'Metro Vancouver' 'Squamish-Lillooet D' 'Gabriola']


In [5]:
attractions = tourist_list[["name","type","subtypes","city","full_address","latitude","longitude","working_hours","rating","reviews"]]
#attractions

In [6]:
#attraction_vancouver = attractions[attractions["subtypes"].str.contains("Tourist attraction",na = False)]
#attraction_vancouver_2 = attractions_vancouver[attractions_vancouver["city"].str.contains("Vancouver",na = False)]
attraction_vancouver_2 = attractions[attractions["city"].str.contains("Vancouver",na = False)]
attractions_clean_review = attraction_vancouver_2.dropna(axis = 0)
attractions_clean_review_sort = attractions_clean_review.sort_values("reviews")
attractions_clean_review_sort_reorder = attractions_clean_review_sort.reset_index(drop=True)
attractions_clean_review_sort_reorder
vancouver_list = attractions_clean_review_sort_reorder
#vancouver_list.tail(20)

In [7]:
#selected 10 attractions
vancouver_top = vancouver_list.tail(12)
vancouver_top.reset_index(drop = True, inplace = True)
vancouver_top

name                type  \
0                Vancouver Aquarium  Tourist attraction   
1         VanDusen Botanical Garden  Tourist attraction   
2                 CF Pacific Centre       Shopping mall   
3                     Science World  Tourist attraction   
4                   Grouse Mountain  Tourist attraction   
5              Queen Elizabeth Park  Tourist attraction   
6                 English Bay Beach  Tourist attraction   
7               Gastown Steam Clock  Tourist attraction   
8                      Canada Place   Convention center   
9    Granville Island Public Market              Market   
10  Capilano Suspension Bridge Park  Tourist attraction   
11                     Stanley Park  Tourist attraction   

                                             subtypes             city  \
0   Tourist attraction, Education center, Non-prof...        Vancouver   
1          Tourist attraction, Park, Botanical garden        Vancouver   
2                                       Shopping mall        Vancouver   
3   Tourist attraction, Event venue, Non-profit or...        Vancouver   
4   Tourist attraction, Hiking area, Ice skating r...  North Vancouver   
5                Tourist attraction, Playground, Park        Vancouver   
6              Tourist attraction, Park, Public beach        Vancouver   
7             Tourist attraction, Historical landmark        Vancouver   
8               Convention center, Tourist attraction        Vancouver   
9                           Market, Fresh food market        Vancouver   
10                         Tourist attraction, Bridge  North Vancouver   
11                           Tourist attraction, Park        Vancouver   

                                         full_address   latitude   longitude  \
0               845 Avison Way, Vancouver, BC V6G 3E2  49.300488 -123.130877   
1                  5251 Oak St, Vancouver, BC V6M 4H1  49.239569 -123.132541   
2             701 W Georgia St, Vancouver, BC V7Y 1G5  49.283398 -123.117540   
3               1455 Quebec St, Vancouver, BC V6A 3Z7  49.273376 -123.103834   
4   6400 Nancy Greene Way, North Vancouver, BC V7R...  49.370244 -123.098686   
5               4600 Cambie St, Vancouver, BC V5Z 2Z1  49.241757 -123.112619   
6                    Beach Ave, Vancouver, BC V6C 3C1  49.286311 -123.143486   
7                 305 Water St, Vancouver, BC V6B 1B9  49.284409 -123.108872   
8                999 Canada Pl, Vancouver, BC V6C 3T4  49.288825 -123.111121   
9   Public Market, 1689 Johnston St, Vancouver, BC...  49.272701 -123.135215   
10      3735 Capilano Rd, North Vancouver, BC V7R 4J1  49.342861 -123.114924   
11                              Vancouver, BC V6G 1Z4  49.304258 -123.144252   

                                        working_hours  rating  reviews  
0   {"Sunday": "10a.m.-5p.m.", "Monday": "10a.m.-5...     4.5   8497.0  
1   {"Sunday": "10a.m.-3p.m.,4-10p.m.", "Monday": ...     4.6   8668.0  
2   {"Sunday": "11a.m.-7p.m.", "Monday": "10a.m.-7...     4.2   9601.0  
3   {"Sunday": "10a.m.-5p.m.", "Monday": "10a.m.-5...     4.5  10601.0  
4   {"Sunday": "9a.m.-9:30p.m.", "Monday": "9a.m.-...     4.6  11742.0  
5   {"Sunday": "6a.m.-10p.m.", "Monday": "6a.m.-10...     4.7  12822.0  
6   {"Sunday": "6a.m.-10p.m.", "Monday": "6a.m.-10...     4.7  13521.0  
7   {"Sunday": "Open 24 hours", "Monday": "Open 24...     4.4  16170.0  
8   {"Sunday": "8a.m.-12p.m.,1-4p.m.", "Monday": "...     4.6  16243.0  
9   {"Sunday": "9a.m.-6p.m.", "Monday": "9a.m.-6p....     4.6  18953.0  
10  {"Sunday": "11a.m.-9p.m.", "Monday": "11a.m.-9...     4.6  24457.0  
11  {"Sunday": "9a.m.-5p.m.", "Monday": "9a.m.-5p....     4.8  40284.0

In [8]:
vancouver_top["name"]

0                  Vancouver Aquarium
1           VanDusen Botanical Garden
2                   CF Pacific Centre
3                       Science World
4                     Grouse Mountain
5                Queen Elizabeth Park
6                   English Bay Beach
7                 Gastown Steam Clock
8                        Canada Place
9      Granville Island Public Market
10    Capilano Suspension Bridge Park
11                       Stanley Park
Name: name, dtype: object

In [9]:
attraction_name = vancouver_top["name"]
min_visiting_time = [0,1.5,2,0.24,2,2.5,1,0.4,0.25,0.75,0.5,1,0.5]
max_visiting_time = [0,3,3,0.75,3,3,2,2,1,1,1.5,2.5,3]

def visiting_time_cal(min_visiting_time,max_visiting_time):
    avg_visiting_time = []
    avg_time = 0
    for i in range(len(min_visiting_time)):
        if min_visiting_time[i] != 0:
            avg_time = (min_visiting_time[i]+ max_visiting_time[i])/2
        else:
            avg_time = max_visiting_time[i]
        avg_visiting_time.append(avg_time)
    return avg_visiting_time
avg_visiting_time = visiting_time_cal(min_visiting_time,max_visiting_time)
print(avg_visiting_time)
print(sum(avg_visiting_time))

[0, 2.25, 2.5, 0.495, 2.5, 2.75, 1.5, 1.2, 0.625, 0.875, 1.0, 1.75, 1.75]
19.195


Now we aim to visiting vancouver attractions as much as possible with shorest visiting time (convert both travelling time and visiting time)

## Create data

In [10]:
addresses= ['Universtiy+of+British+Columbia', #depot
                'Vancouver+Aquarium',
                'VanDusen+Botanical+Garden',
                        'CF+Pacific+Centre', 
                       'Science+World',
                'Grouse+Mountain',
                       'Queen+Elizabeth+Park',
                       'English+Bay+Beach',
                       'Gastown+Steam+Clock',
                       'Canada+Place',
                       'Granville+Island+Public+Market',
                       'Capilano+Suspension+Bridge+Park',
                       'Stanley+Park'
                      ]
avg_visiting_time = visiting_time_cal(min_visiting_time,max_visiting_time)

In [11]:
def create_data(addresses):
    """Creates the data."""
    data = {}
    data['API_key'] = "AIzaSyAEKN-xcnWtB3c65ErptbVLrZYlpRhST9o"
    data['addresses'] = addresses
    return data
create_data(addresses)

{'API_key': 'AIzaSyAEKN-xcnWtB3c65ErptbVLrZYlpRhST9o',
 'addresses': ['Universtiy+of+British+Columbia',
  'Vancouver+Aquarium',
  'VanDusen+Botanical+Garden',
  'CF+Pacific+Centre',
  'Science+World',
  'Grouse+Mountain',
  'Queen+Elizabeth+Park',
  'English+Bay+Beach',
  'Gastown+Steam+Clock',
  'Canada+Place',
  'Granville+Island+Public+Market',
  'Capilano+Suspension+Bridge+Park',
  'Stanley+Park']}

## create distance matrix

In [12]:
## create distance matrix
def create_distance_matrix(data):
    addresses = data["addresses"]
    API_key = data["API_key"]
    # Distance Matrix API only accepts 100 elements per request, so get rows in multiple requests.
    max_elements = 100
    num_addresses = len(addresses) 
    # Maximum number of rows that can be computed per request (6 in this example).
    max_rows = max_elements // num_addresses
    # num_addresses = q * max_rows + r .
    q, r = divmod(num_addresses, max_rows)
    dest_addresses = addresses
    distance_matrix = []
    # Send q requests, returning max_rows rows per request.
    for i in range(q):
        origin_addresses = addresses[i * max_rows: (i + 1) * max_rows]
        response = send_request(origin_addresses, dest_addresses, API_key)
        distance_matrix += build_distance_matrix(response)

    # Get the remaining remaining r rows, if necessary.
    if r > 0:
        origin_addresses = addresses[q * max_rows: q * max_rows + r]
        response = send_request(origin_addresses, dest_addresses, API_key)
        distance_matrix += build_distance_matrix(response)
    return distance_matrix

def send_request(origin_addresses, dest_addresses, API_key):
    """ Build and send request for the given origin and destination addresses."""
    def build_address_str(addresses):
    # Build a pipe-separated string of addresses
        address_str = ''
        for i in range(len(addresses) - 1):
            address_str += addresses[i] + '|'
        address_str += addresses[-1]
        return address_str

    request = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial'
    origin_address_str = build_address_str(origin_addresses)
    dest_address_str = build_address_str(dest_addresses)
    request = request + '&origins=' + origin_address_str + '&destinations=' + \
                       dest_address_str + '&key=' + API_key
    jsonResult = urllib.request.urlopen(request).read()
    response = json.loads(jsonResult)
    return response

def build_distance_matrix(response):
    distance_matrix = []
    for row in response['rows']:
        row_list = [row['elements'][j]['distance']['value'] for j in range(len(row['elements']))]
        distance_matrix.append(row_list)
    return distance_matrix

## create duration matrix

In [13]:
# create duration matrix for transport
def create_duration_matrix(data):
    addresses = data["addresses"]
    API_key = data["API_key"]
    # Distance Matrix API only accepts 100 elements per request, so get rows in multiple requests.
    max_elements = 100
    num_addresses = len(addresses) 
    # Maximum number of rows that can be computed per request 
    max_rows = max_elements // num_addresses
    # num_addresses = q * max_rows + r 
    q, r = divmod(num_addresses, max_rows)
    dest_addresses = addresses
    duration_matrix = []
    # Send q requests, returning max_rows rows per request.
    for i in range(q):
        origin_addresses = addresses[i * max_rows: (i + 1) * max_rows]
        response = send_request(origin_addresses, dest_addresses, API_key)
        duration_matrix += build_duration_matrix(response)

    # Get the remaining remaining r rows, if necessary.
    if r > 0:
        origin_addresses = addresses[q * max_rows: q * max_rows + r]
        response = send_request(origin_addresses, dest_addresses, API_key)
        duration_matrix += build_duration_matrix(response)
    return duration_matrix

def build_duration_matrix(response):
    duration_matrix = []
    for row in response['rows']:
        row_list = [row['elements'][j]['duration']['value'] for j in range(len(row['elements']))]
        duration_matrix.append(row_list)
    return duration_matrix


In [14]:
data = create_data(addresses)
print(data)
# addresses = data['addresses']
# API_key = data['API_key']
#create distance matrix (unit: m)
distance_matrix = create_distance_matrix(data)
print(np.matrix(distance_matrix))
#create duration matrix (unit: sec)
duration_matrix = create_duration_matrix(data)
print(np.matrix(duration_matrix))

{'API_key': 'AIzaSyAEKN-xcnWtB3c65ErptbVLrZYlpRhST9o', 'addresses': ['Universtiy+of+British+Columbia', 'Vancouver+Aquarium', 'VanDusen+Botanical+Garden', 'CF+Pacific+Centre', 'Science+World', 'Grouse+Mountain', 'Queen+Elizabeth+Park', 'English+Bay+Beach', 'Gastown+Steam+Clock', 'Canada+Place', 'Granville+Island+Public+Market', 'Capilano+Suspension+Bridge+Park', 'Stanley+Park']}
[[    0 14064  9115 11089 12085 23095 10063 11615 12086 11733  9686 19535
  12247]
 [14902     0 11076  4903  7012 11220 10090  4275  5601  5028  8302  7660
   3112]
 [ 8562  9559     0  6228  5425 18589  2697  7036  6291  7206  4629 15030
   7668]
 [ 9926  3055  6100     0  2105 12085  5117  2525  1169   756  3326  8526
   1696]
 [10970  5423  5340  2241     0 14454  4193  4422  1662  2690  4054 10894
   4065]
 [22394 12810 18568 12395 14504     0 17582 11767 13093 12520 15794  3567
   8458]
 [ 9608  7837  1071  4506  4799 16868     0  7498  4855  5441  4952 13308
   6478]
 [10343  2522  7446  2841  4185 11552 

## create data model for TSP

In [15]:
def create_data_model(distance_matrix,duration_matrix,avg_visiting_time):
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = distance_matrix
    data['duration_matrix'] = duration_matrix
    data['avg_visiting_time'] = avg_visiting_time
    data['num_vehicles'] = 1
    data['depot'] = 0
    return data
#create_data_model(distance_matrix,duration_matrix,avg_visiting_time)

In [16]:
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

In [17]:
distance_matrix = distance_matrix
duration_matrix = duration_matrix
avg_visiting_time = avg_visiting_time
#address_list = address_list
    
data = create_data_model(distance_matrix,duration_matrix,avg_visiting_time)
#print(data)
manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
routing = pywrapcp.RoutingModel(manager)

## TSP calculating

In [18]:
def TSP_route(address_list,distance_matrix,duration_matrix,avg_visiting_time):
    distance_matrix = distance_matrix
    duration_matrix = duration_matrix
    avg_visiting_time = avg_visiting_time
    address_list = address_list
    
    data = create_data_model(distance_matrix,duration_matrix,avg_visiting_time)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    
    transit_callback_index = routing.RegisterTransitCallback(duration_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
    
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    solution = routing.SolveWithParameters(search_parameters)
    if solution:
        print_solution(address_list,manager, routing, solution, avg_visiting_time)
        #routes = get_routes(address_list,solution, routing, manager)
        #routes_list.append(routes)

In [19]:
def duration_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    avg_visiting_time = manager.IndexToNode(to_index)
    return (data['duration_matrix'][from_node][to_node])
transit_callback_index = routing.RegisterTransitCallback(duration_callback)
#transit_callback_index

In [20]:
def print_solution(address_list,manager, routing, solution,avg_visiting_time):
    """Prints solution on console."""
    transport_time = solution.ObjectiveValue()/60/60
    visit_time = avg_visiting_time
    visiting_time = sum(visit_time)
    print('Objective: {} hours'.format(transport_time))
    print('Visiting time: {} hours'.format(visiting_time))
    print('Total time: {}hours'.format(transport_time + visiting_time))
    index = routing.Start(0)
    plan_output = 'Route for vehicle 0:\n'
    route_duration = 0
    while not routing.IsEnd(index):
        plan_output += ' {} ->'.format(address_list[manager.IndexToNode(index)])
        previous_index = index
        index = solution.Value(routing.NextVar(index))
        route_duration += routing.GetArcCostForVehicle(previous_index, index, 0)
    plan_output += ' {}\n'.format(address_list[manager.IndexToNode(index)])
    print(plan_output)
    plan_output += 'Route duration: {}miles\n'.format(route_duration)

In [21]:
TSP_route(addresses,distance_matrix,duration_matrix, avg_visiting_time)

Objective: 2.143333333333333 hours
Visiting time: 19.195 hours
Total time: 21.338333333333335hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> English+Bay+Beach -> Stanley+Park -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> CF+Pacific+Centre -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia



## routes saving

In [22]:
def get_routes(address_list,solution, routing, manager):
    """Get vehicle routes from a solution and store them in an array."""
    # Get vehicle routes and store them in a two dimensional array whose
    # i,j entry is the jth location visited by vehicle i along its route.
    routes = []
    for route_nbr in range(routing.vehicles()):
        index = routing.Start(route_nbr)
        route = [address_list[manager.IndexToNode(index)]]
        while not routing.IsEnd(index):
            index = solution.Value(routing.NextVar(index))
            route.append(address_list[manager.IndexToNode(index)])
    routes.append(route)
    return routes

In [23]:
# routes = get_routes(solution, routing, manager)
# # Display the routes.
# for i, route in enumerate(routes):
#     print('Route', i, route)

In [24]:
def reduce_attraction_check(total_time_cost):
    time_limit = 8*60
    if time_limit >= total_time_cost:
        return True
    else:
        return False

In [25]:
list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - 1)))
#print(len(list_selected))
new_lists = []
for selected in list_selected:
    selected = list(selected)
    selected.insert(0,0)
    new_lists.append(selected)
new_lists = np.array(new_lists)
print(new_lists)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 12]
 [ 0  1  2  3  4  5  6  7  8  9 11 12]
 [ 0  1  2  3  4  5  6  7  8 10 11 12]
 [ 0  1  2  3  4  5  6  7  9 10 11 12]
 [ 0  1  2  3  4  5  6  8  9 10 11 12]
 [ 0  1  2  3  4  5  7  8  9 10 11 12]
 [ 0  1  2  3  4  6  7  8  9 10 11 12]
 [ 0  1  2  3  5  6  7  8  9 10 11 12]
 [ 0  1  2  4  5  6  7  8  9 10 11 12]
 [ 0  1  3  4  5  6  7  8  9 10 11 12]
 [ 0  2  3  4  5  6  7  8  9 10 11 12]]


In [26]:
def delete_attractions():
    n = len(addresses)
    unvisiting = list(range(n))
    new_attraction_matrix = np.tile(unvisiting,(n,1))
    new_list = []
    
    #remove nodes from 1, because UBC should be our start point
    for i in range(1,n):
        remove_index = i
        new_list.append(np.delete(new_attraction_matrix[i],remove_index))
    new_list = np.array(new_list)
    return new_list
    
new_lists = delete_attractions()
#new_lists

#### create new attractions list and its avg_visiting_time

In [27]:
def new_attraction_create(addresses,new_lists):
    new_address_list = []
    for i in range(len(new_lists)):
        num_list = new_lists[i]
        new_address = []
        for j in num_list:
            new_address.append(addresses[j])
        new_address_list.append(new_address)
    return new_address_list
new_address_list = new_attraction_create(addresses,new_lists)
#new_address_list

In [28]:
def new_avg_time_create(avg_visiting_time,new_lists):
    new_avg_time_list = []
    for i in range(len(new_lists)):
        num_list = new_lists[i]
        new_avg_time = []
        for j in num_list:
            new_avg_time.append(avg_visiting_time[j])
        new_avg_time_list.append(new_avg_time)
    return new_avg_time_list
new_avg_visiting_time_list = new_avg_time_create(avg_visiting_time,new_lists)
#new_avg_visiting_time_list

### start selection 

In [29]:
def TSP_route_selected(address_list,distance_matrix,duration_matrix,avg_visiting_time):
    distance_matrix = distance_matrix
    duration_matrix = duration_matrix
    avg_visiting_time = avg_visiting_time
    address_list = address_list
    
    data = create_data_model(distance_matrix,duration_matrix,avg_visiting_time)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    
    transit_callback_index = routing.RegisterTransitCallback(duration_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
    
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    solution = routing.SolveWithParameters(search_parameters)
    visiting_time = sum(avg_visiting_time)
    
    if (solution.ObjectiveValue()/60/60 + visiting_time) < 8:
        print_solution(address_list,manager, routing, solution, avg_visiting_time)
#     else:
#         print("Do not satisfied")

### create new selected tourist attractions list by combinatorial number

In [30]:
def new_list_create(n):
    list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - n)))
    print(len(list_selected))
    new_lists = []
    for selected in list_selected:
        selected = list(selected)
        selected.insert(0,0)
        new_lists.append(selected)
    new_lists = np.array(new_lists)
    print(new_lists.shape)
    new_address_list = new_attraction_create(addresses,new_lists)
    new_avg_visiting_time_list = new_avg_time_create(avg_visiting_time,new_lists)
    return new_lists,new_address_list,new_avg_visiting_time_list

In [31]:
new_lists,new_address_list,new_avg_visiting_time_list = new_list_create(1)

12
(12, 12)


In [32]:
#remove one attractions from list
for i in range(0,len(new_address_list)):
    address_new = new_address_list[i]
    avg_visiting_time_new = new_avg_visiting_time_list[i]
    data_new = create_data(address_new)
    
    
    
    distance_matrix_new = create_distance_matrix(data_new)
    duration_matrix_new = create_duration_matrix(data_new)
    
    
    data = create_data_model(distance_matrix_new,duration_matrix_new,avg_visiting_time_new)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route(address_new,distance_matrix_new,duration_matrix_new,avg_visiting_time_new)

Objective: 2.185 hours
Visiting time: 17.445 hours
Total time: 19.63hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> English+Bay+Beach -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia

Objective: 2.136111111111111 hours
Visiting time: 17.445 hours
Total time: 19.581111111111113hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> English+Bay+Beach -> Stanley+Park -> Vancouver+Aquarium -> Grouse+Mountain -> CF+Pacific+Centre -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia

Objective: 1.9702777777777778 hours
Visiting time: 18.195 hours
Total time: 20.165277777777778hours
Route for vehicle 0:
 Universtiy+of+British+Colu

Delete one attraction does not satify the time limit.Start to delete for two

In [33]:
list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - 2)))
print(len(list_selected))
new_lists_2 = []
for selected in list_selected:
    selected = list(selected)
    selected.insert(0,0)
    new_lists_2.append(selected)
new_lists_2 = np.array(new_lists_2)
print(new_lists_2.shape)
comb(12,2)

66
(66, 11)


66

In [34]:
new_address_list_2 = new_attraction_create(addresses,new_lists_2)
new_avg_visiting_time_list_2 = new_avg_time_create(avg_visiting_time,new_lists_2)

In [35]:
for i in range(0,len(new_avg_visiting_time_list_2)):
    address_new_2 = new_address_list_2[i]
    avg_visiting_time_new_2 = new_avg_visiting_time_list_2[i]
    data_new_2 = create_data(address_new_2)
    distance_matrix_new_2 = create_distance_matrix(data_new_2)
    duration_matrix_new_2 = create_duration_matrix(data_new_2)
    
    data = create_data_model(distance_matrix_new_2,duration_matrix_new_2,avg_visiting_time_new_2)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route(address_new_2,distance_matrix_new_2,duration_matrix_new_2,avg_visiting_time_new_2)

Objective: 2.1777777777777776 hours
Visiting time: 15.695 hours
Total time: 17.872777777777777hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> English+Bay+Beach -> Vancouver+Aquarium -> Grouse+Mountain -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia

Objective: 1.9036111111111111 hours
Visiting time: 16.445 hours
Total time: 18.34861111111111hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> CF+Pacific+Centre -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> English+Bay+Beach -> Universtiy+of+British+Columbia

Objective: 1.9630555555555556 hours
Visiting time: 16.445 hours
Total time: 18.408055555555556hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanic

Objective: 1.9455555555555555 hours
Visiting time: 16.495 hours
Total time: 18.440555555555555hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Granville+Island+Public+Market -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Stanley+Park -> CF+Pacific+Centre -> Universtiy+of+British+Columbia

Objective: 2.023888888888889 hours
Visiting time: 14.695 hours
Total time: 16.71888888888889hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> English+Bay+Beach -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia

Objective: 1.5897222222222223 hours
Visiting time: 14.695 hours
Total time: 16.28472222222222hours
Route for vehicle 0:
 Universtiy+of+British+Columbia 

Objective: 1.9583333333333333 hours
Visiting time: 18.075 hours
Total time: 20.03333333333333hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> Granville+Island+Public+Market -> English+Bay+Beach -> Stanley+Park -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Canada+Place -> Science+World -> Queen+Elizabeth+Park -> VanDusen+Botanical+Garden -> Universtiy+of+British+Columbia

Objective: 2.0013888888888887 hours
Visiting time: 17.5 hours
Total time: 19.50138888888889hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Queen+Elizabeth+Park -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> Vancouver+Aquarium -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Stanley+Park -> Granville+Island+Public+Market -> Universtiy+of+British+Columbia

Objective: 1.9597222222222221 hours
Visiting time: 17.2 hours
Total time: 19.15972222222222hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDuse

Objective: 1.8169444444444445 hours
Visiting time: 15.745000000000001 hours
Total time: 17.561944444444446hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> Granville+Island+Public+Market -> Stanley+Park -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Science+World -> Queen+Elizabeth+Park -> VanDusen+Botanical+Garden -> Universtiy+of+British+Columbia

Objective: 1.798888888888889 hours
Visiting time: 15.445 hours
Total time: 17.24388888888889hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> Granville+Island+Public+Market -> English+Bay+Beach -> Stanley+Park -> Capilano+Suspension+Bridge+Park -> Grouse+Mountain -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Science+World -> VanDusen+Botanical+Garden -> Universtiy+of+British+Columbia

Objective: 1.7080555555555557 hours
Visiting time: 14.195 hours
Total time: 15.903055555555556hours
Route for vehicle 0:
 Universtiy+of+British+Colum

## delete 2 not satisfies, start delete 3

In [36]:
list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - 3)))
print(len(list_selected))
new_lists_3 = []
for selected in list_selected:
    selected = list(selected)
    selected.insert(0,0)
    new_lists_3.append(selected)
new_lists_3 = np.array(new_lists_3)
print(new_lists_3.shape)
comb(12,3)

220
(220, 10)


220

In [37]:
new_address_list_3 = new_attraction_create(addresses,new_lists_3)
new_avg_visiting_time_list_3 = new_avg_time_create(avg_visiting_time,new_lists_3)

In [38]:
for i in range(0,len(new_avg_visiting_time_list_3)):
    address_new_3 = new_address_list_3[i]
    avg_visiting_time_new_3 = new_avg_visiting_time_list_3[i]
    data_new_3 = create_data(address_new_3)
    distance_matrix_new_3 = create_distance_matrix(data_new_3)
    duration_matrix_new_3 = create_duration_matrix(data_new_3)
    
    data = create_data_model(distance_matrix_new_3,duration_matrix_new_3,avg_visiting_time_new_3)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route_selected(address_new_3,distance_matrix_new_3,duration_matrix_new_3,avg_visiting_time_new_3)

Does not print satisfied result

## delete 3 not satisfies, start delete 4

In [39]:
list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - 4)))
print(len(list_selected))
new_lists_4 = []
for selected in list_selected:
    selected = list(selected)
    selected.insert(0,0)
    new_lists_4.append(selected)
new_lists_4 = np.array(new_lists_4)
print(new_lists_4.shape)

comb(12,4)

495
(495, 9)


495

In [40]:
new_address_list_4 = new_attraction_create(addresses,new_lists_4)
new_avg_visiting_time_list_4 = new_avg_time_create(avg_visiting_time,new_lists_4)

In [41]:
for i in range(0,len(new_avg_visiting_time_list_4)):
    address_new_4 = new_address_list_4[i]
    avg_visiting_time_new_4 = new_avg_visiting_time_list_4[i]
    data_new_4 = create_data(address_new_4)
    distance_matrix_new_4 = create_distance_matrix(data_new_4)
    duration_matrix_new_4 = create_duration_matrix(data_new_4)
    
    data = create_data_model(distance_matrix_new_4,duration_matrix_new_4,avg_visiting_time_new_4)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route_selected(address_new_4,distance_matrix_new_4,duration_matrix_new_4,avg_visiting_time_new_4)

## delete 4 not satisfies, start delete 5

In [42]:
list_selected = list(itertools.combinations([1,2,3,4,5,6,7,8,9,10,11,12], (12 - 5)))
print(len(list_selected))
new_lists_5 = []
for selected in list_selected:
    selected = list(selected)
    selected.insert(0,0)
    new_lists_5.append(selected)
new_lists_5 = np.array(new_lists_5)
print(new_lists_5.shape)

comb(12,5)

792
(792, 8)


792

In [43]:
new_address_list_5 = new_attraction_create(addresses,new_lists_5)
new_avg_visiting_time_list_5 = new_avg_time_create(avg_visiting_time,new_lists_5)

In [44]:
for i in range(0,len(new_avg_visiting_time_list_5)):
    address_new_5 = new_address_list_5[i]
    avg_visiting_time_new_5 = new_avg_visiting_time_list_5[i]
    data_new_5 = create_data(address_new_5)
    distance_matrix_new_5 = create_distance_matrix(data_new_5)
    duration_matrix_new_5 = create_duration_matrix(data_new_5)
    
    data = create_data_model(distance_matrix_new_5,duration_matrix_new_5,avg_visiting_time_new_5)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route_selected(address_new_5,distance_matrix_new_5,duration_matrix_new_5,avg_visiting_time_new_5)

Does not print a time_limit_satisfied route

## delete 5 not satisfies, start delete 6

In [45]:
new_lists_6,new_address_list_6,new_avg_visiting_time_list_6 = new_list_create(6)

924
(924, 7)


In [46]:
for i in range(0,len(new_avg_visiting_time_list_6)):
    address_new_6 = new_address_list_6[i]
    avg_visiting_time_new_6 = new_avg_visiting_time_list_6[i]
    data_new_6 = create_data(address_new_6)
    distance_matrix_new_6 = create_distance_matrix(data_new_6)
    duration_matrix_new_6 = create_duration_matrix(data_new_6)
    
    data = create_data_model(distance_matrix_new_6,duration_matrix_new_6,avg_visiting_time_new_6)
    #print(data)
    manager = pywrapcp.RoutingIndexManager(len(data['duration_matrix']),
                                       data['num_vehicles'], data['depot'])
    routing = pywrapcp.RoutingModel(manager)
    TSP_route_selected(address_new_6,distance_matrix_new_6,duration_matrix_new_6,avg_visiting_time_new_6)

Objective: 1.353888888888889 hours
Visiting time: 6.445 hours
Total time: 7.798888888888889hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> Granville+Island+Public+Market -> English+Bay+Beach -> Vancouver+Aquarium -> Canada+Place -> Gastown+Steam+Clock -> CF+Pacific+Centre -> Universtiy+of+British+Columbia

Objective: 1.2519444444444443 hours
Visiting time: 6.695 hours
Total time: 7.946944444444444hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> VanDusen+Botanical+Garden -> Granville+Island+Public+Market -> Gastown+Steam+Clock -> Canada+Place -> CF+Pacific+Centre -> English+Bay+Beach -> Universtiy+of+British+Columbia

Objective: 1.1927777777777777 hours
Visiting time: 6.695 hours
Total time: 7.887777777777778hours
Route for vehicle 0:
 Universtiy+of+British+Columbia -> Granville+Island+Public+Market -> Science+World -> Gastown+Steam+Clock -> Canada+Place -> CF+Pacific+Centre -> English+Bay+Beach -> Universtiy+of+British+Columbia

Objective: 1.286388888888889 h

13 routes which less than 8 hours